version: '3'

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_acourse
    ports: 
      - "8080:80"
    volumes: 
      - ./src:/var/www/html
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql_acourse
    restart: unless-stopped
    tty: true
    ports:  
      - "33060:3306"
    volumes:
      - ./containers/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: acourse
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_acourse
    volumes:
     - ./src:/var/www/html
    ports:
     - "9090:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer_acourse
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    image: node:14.17.0
    container_name: npm_acourse
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan_acourse
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel
